# Generated by Django 5.1.6 on 2025-02-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_passengers_alter_ride_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='seats_available',
            new_name='total_seats',
        ),
    ]
