# Generated by Django 5.1.6 on 2025-03-26 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Foto de perfil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de teléfono')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de residencia')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('has_vehicle', models.BooleanField(default=False, verbose_name='¿Tienes vehículo?')),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo del vehículo')),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año del vehículo')),
                ('vehicle_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color del vehículo')),
                ('vehicle_features', models.TextField(blank=True, null=True, verbose_name='Características adicionales')),
                ('pref_music', models.CharField(choices=[('any', 'Cualquiera'), ('pop', 'Pop'), ('rock', 'Rock'), ('electronic', 'Electrónica'), ('classical', 'Clásica'), ('none', 'Prefiero silencio')], default='any', max_length=20, verbose_name='Música')),
                ('pref_talk', models.CharField(choices=[('chatty', 'Me gusta conversar'), ('quiet', 'Prefiero silencio'), ('depends', 'Depende del momento')], default='depends', max_length=20, verbose_name='Conversación')),
                ('pref_pets', models.BooleanField(default=False, verbose_name='Acepto mascotas')),
                ('pref_smoking', models.BooleanField(default=False, verbose_name='Permito fumar')),
                ('email_notifications', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('ride_notifications', models.BooleanField(default=True)),
                ('profile_visible', models.BooleanField(default=True)),
                ('show_rides_history', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
