# Generated by Django 5.1.6 on 2025-03-26 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('report_type', models.CharField(choices=[('payment', 'Pago'), ('ride', 'Viaje'), ('user', 'Usuario'), ('system', 'Sistema')], default='system', max_length=10, verbose_name='Tipo')),
                ('importance', models.CharField(choices=[('normal', 'Normal'), ('important', 'Importante'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Importancia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('read', models.BooleanField(default=False, verbose_name='Leído')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
