# Generated by Django 5.1.6 on 2025-03-26 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_idempotency_key'),
        ('reports', '0003_alter_report_options_report_response_and_more'),
        ('rides', '0003_rename_seats_available_ride_total_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='payments.payment', verbose_name='Pago reportado'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_in', to=settings.AUTH_USER_MODEL, verbose_name='Usuario reportado'),
        ),
        migrations.AddField(
            model_name='report',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='rides.ride', verbose_name='Viaje reportado'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta'),
        ),
    ]
