# Generated by Django 5.1.6 on 2025-03-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_vehicle',
            field=models.BooleanField(default=False, verbose_name='¿Tienes vehículo?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de residencia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_music',
            field=models.CharField(choices=[('any', 'Cualquiera'), ('pop', 'Pop'), ('rock', 'Rock'), ('electronic', 'Electrónica'), ('classical', 'Clásica'), ('none', 'Prefiero silencio')], default='any', max_length=20, verbose_name='Música'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_pets',
            field=models.BooleanField(default=False, verbose_name='Acepto mascotas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_smoking',
            field=models.BooleanField(default=False, verbose_name='Permito fumar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_talk',
            field=models.CharField(choices=[('chatty', 'Me gusta conversar'), ('quiet', 'Prefiero silencio'), ('depends', 'Depende del momento')], default='depends', max_length=20, verbose_name='Conversación'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color del vehículo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_features',
            field=models.TextField(blank=True, null=True, verbose_name='Características adicionales'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo del vehículo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año del vehículo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de teléfono'),
        ),
    ]
